# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - tudorDotNetApp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Create Resource Group
        run: |
          az group create --name DevProjectDotNet --location northeurope
          az webapp list --query "[?state=='Running']"
        
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x  # replace x with the latest patch version of .NET 6.0

    #  - name: Create Web App
    #    run: |
    #      az webapp create --name tudorDotNetApp --resource-group DevProjectDotNet --plan tudorPlan --runtime "DOTNET|6.0" --deployment-local-git
     
     
      - name: Create SQL Server
        run: |
          az sql server create --name tudorSQLServer1 --resource-group DevProjectDotNet --location northeurope --admin-user myadmin --admin-password AdminPassword1234!@#$

      - name: Create Firewall Rule
        run: |
          az sql server firewall-rule create --name AllowAllWindowsAzureIps --resource-group DevProjectDotNet --server tudorSQLServer1 --start-ip-address 0.0.0.0 --end-ip-address 0.0.0.0

      - name: Create SQL Database
        run: |
          az sql db create --name tudorDatabase1 --resource-group DevProjectDotNet --server tudorSQLServer1 --tier Basic --edition Basic --collation SQL_Latin1_General_CP1_CI_AS

      #This command creates an autoscale setting for the tudorApp web app. It specifies that the app should have at least 1 instance, at most 5 instances, and maintain an average CPU utilization of 70% over a 5-minute period. It also specifies that the time grain for evaluating the condition should be 5 minutes. You can adjust these values to suit your needs.
      #- name: Create Autoscale settings
      #  run: |
       #   az monitor autoscale create --resource-group tudorDevopsProject --resource tudorApp --resource-type Microsoft.Web/sites --name tudorAutoscale --min-count 1 --max-count 3 --count 2
      #    az monitor autoscale rule create -g tudorDevopsProject --autoscale-name tudorApp --scale out 1 --condition "CpuPercentage > 80 avg 5m"
      
      - name: Create Alert Rule
        run: |
          scope=$(az vm show -g DevProjectDotNet -n VM10 --query "id" -o tsv)
          condition=$(az monitor metrics alert condition create --aggregation Average --metric "Percentage CPU" --op GreaterThan --type static --threshold 90 --output tsv)
          az monitor metrics alert create --name tudorAlert1 --resource-group DevProjectDotNet --scopes $(echo $scope | tr -d '\r') --condition "avg Percentage CPU > 90" --description "Test High CPU" --debug
        
      - name: Create App Insights
        run : |
          az config set extension.use_dynamic_install=yes_without_prompt
          az monitor app-insights component create --app tudorInsights1 --location northeurope --resource-group DevProjectDotNet --application-type web --retention-time 30
        
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'tudorDotNetApp'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_475965E3E2A0421B8897B39D65D39380 }}
          package: .
